--- #YAML:1.0
name:                Archive-Zip
version:             1.25
abstract:            Provide an interface to ZIP archive files.
license:             perl
author:              
    - Ned Konz <perl@bike-nomad.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Compress::Zlib:                1.14
    File::Basename:                0
    File::Copy:                    0
    File::Find:                    0
    File::Path:                    0
    File::Spec:                    0.80
    File::Temp:                    0
    IO::File:                      0
    IO::Handle:                    0
    IO::Seekable:                  0
    Test::More:                    0.42
    Time::Local:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
